const express = require("express");
const registerUsersRoute = require("./registerUsers");
const loginUsersRoute = require("./loginUsers");
const postsRoutes = require("./addPosts");
const getAllPostsRoute = require("./getAllPosts");
const addCommentRoute = require("./addComment");
const likePostRoute = require("./likePost");
const getAllPostsCommentsRoute = require("./getAllPostsComments");
const dislikePostRoute = require("./dislikePost");
const deletePost = require("./deletePost");
const router = express.Router();
router.use(registerUsersRoute);
router.use(loginUsersRoute);
router.use(postsRoutes);
router.use(getAllPostsRoute);
router.use(addCommentRoute);
router.use(getAllPostsCommentsRoute);
router.use(likePostRoute);
router.use(dislikePostRoute);
router.use(deletePost);
module.exports = router;
